# XLEAP Detector

This notebook detects XLEAP using undulator taper, and quantifies the taper in MeV/fs, and reports which undulators are lasing.

## Theory (see Zhirong's book, Ch. 2.4)

In an undulator with magnetic field strength $B_0$ and wavenumber $k_u$, the electrons encounter a magnetic field in $\hat y$

$$
\vec{B}_u = B_0 \sin(k_u z) \hat y
$$

that produces a force in $\hat x$:

$$\begin{align*}
\dot {\vec p} = \partial_t (\gamma mc \vec \beta)&= -e (\cancel{\vec E} + \vec v \times \vec B) \\
&= -e(\beta c \hat z) \times B_0 \sin(k_u z) \hat y \\
&= +e\beta c B_0 \sin(k_u z) \hat x \\
\end{align*}
$$
Neglecting energy losses from steering radiation, we take $\dot \gamma = 0$ and integrate (taking $\beta_x = 0$ at $t=0$ from before the undulator) to find $\beta_x$:
$$
\begin{align*}
\dot \beta_x &= \frac{e \beta c B_0}{\gamma m c} \sin(k_u z) = \frac{e \beta B_0}{\gamma m} \sin(k_u \beta c t) \tag{$\beta_z \approx \beta \lesssim 1$} \\
\beta_x &= \left. \frac{e \beta B_0}{\gamma m k_u \beta c} \cos(k_u \beta c t)\right \vert_0^t \\
&= \frac{e B_0}{\gamma k_u m c} \cos(k_u \beta c t) \\
&= \frac{1}{\gamma}\underbrace{\frac{e B_0}{k_u m c}}_K \cos(k_u z) \coloneqq \boxed{\frac{K}{\gamma} \cos(k_u z)}

\end{align*}
$$

Again neglecting energy losses from steering radiation, we say that energy $\gamma mc^2$ and therefore total velocity $\beta$ is conserved from before the undulator, but once inside the undulator, the velocity is split between $x$ and $z$ components:

$$
\begin{align*}
{\vec \beta}^2 &= \beta_z^2 + \beta_x^2 \\
\beta_z^2 &= \vec \beta^2 - \beta_x^2 = \left(1 - \frac {1}{\gamma^2} \right) - \beta_x^2 \\
\beta_z &= \sqrt{1-\frac{1}{\gamma^2}-\beta_x^2} \\ 
&\approx 1- \frac{1}{2\gamma^2} - \frac{K^2}{2\gamma^2}\cos^2(k_u z) \tag{$\sqrt{1-\varepsilon}\approx 1-\varepsilon/2$} \\
\langle \beta_z \rangle &= 1- \frac{1}{2\gamma^2} - \frac{K^2}{2\gamma^2}\left\langle\cos^2({k_u z})\right\rangle = 1- \frac{1}{2\gamma^2} - \frac{K^2}{4\gamma^2} \\
&= 1- \left(\frac{1+K^2/2}{2\gamma^2}\right)
\end{align*}
$$
So the light outruns the electrons by $\Delta \beta = (1+K^2/2)/2\gamma^2$. To achieve resonance, we want the radiation to slip ahead of the electrons by one radiation wavelength $\lambda_r$ per undulator period $\lambda_u$. Light covers an undulator period in time $T = \lambda_u/c$, during which time the electrons fall behind by a distance $\Delta \beta c T = \lambda_u(1+K^2/2)/2\gamma^2$, called the **slippage length**. Therefore we set the radiation wavelength equal to the slippage length so that the radiation and undulator fields remain in phase:
$$
\lambda_r = \frac{\lambda_u}{2\gamma^2}\left(1+\frac{K^2}{2}\right)
$$

Meanwhile, space charge forces create an energy spread within the current spike by pushing head electrons forward and tail electrons backward. The radiation slips from lower-energy to higher-energy slices of electrons: $\gamma \to \gamma + \Delta \gamma$. Due to the taper, $K$ also increases downstream: $K \to K + \Delta K$. To maintain resonance, we now need
$$
\lambda_r = \frac{\lambda_u}{2(\gamma + \Delta \gamma)^2}\left(1+\frac{(K + \Delta K)^2}{2}\right)
$$

Therefore, given a $\Delta K$, we can find the corresponding $\Delta \gamma$ needed to maintain resonance:
$$
\begin{align*}
\lambda_r = \frac{\lambda_u}{2\gamma^2}\left(1+\frac{K^2}{2}\right) &= \frac{\lambda_u}{2(\gamma+\Delta \gamma)^2}\left(1+\frac{(K+\Delta K)^2}{2}\right) \\
\implies \Delta \gamma &= \gamma\left(\sqrt{1+\frac{(K+\Delta K/2)\Delta K}{1+K^2/2}}-1\right) \\
&\approx \gamma\left(\frac{K\Delta K + \Delta K^2/2}{K^2+2}\right) \sim \gamma\left(\frac{\Delta K}{K} + \mathcal{O}\left(\left[\frac{\Delta K}{K}\right]^2\right)\right)
\end{align*}
$$

## Implementation

We do a "coarse sweep" between `start` and `end` times, taking snapshots at intervals of `coarse_delta`.
We are interested in three things:
1. Whether XLEAP is happening, indicated by the presence of at least one lasing tapered group of undulators;
2. Which undulators are lasing, as a boolean array (or number of undulators, if we sum);
3. The undulator taper in MeV/fs, calculated by
    
    a) taking the median of the sorted list of $\Delta K$ within the lasing group, 
    
    b) converting to $\Delta \gamma$, and
    
    c) dividing by one undulator length in units of time, $L_u/c$

In [1]:
import meme
import os, re
import numpy as np
from datetime import timedelta, datetime as dt

start = dt(2026, 6, 1, 0, 0)
end = dt.now()
coarse_delta = timedelta(hours=4)
snapshot_delta = timedelta(seconds=3)

## Data collection

We get $\lambda_u$ as a per-undulator PV field ending in `:LAMBDA_U`. We take the length of an undulator $L_u$ as 3.4 m, ignoring the spaces between undulators since negligible slippage occurs without the magnetic field bleeding $\beta_z$ into $\beta_x$.

We get $\gamma$ from the beam dump PV `BEND:DMPS:400:BACT`, which reports the strength of the beam dump magnet not in teslas, but in **GeV/c**, the momentum of beam energy being deflected ($\gamma mc^2 / c = \gamma mc$).

Finally, we take a snapshot of the series of undulator $K$ values. We take $K$ as the first $K$ in the most upstream "hockey stick" region -- that is, a group of at least $n=4$ undulators whose $K$'s are increasing by at least $4\rho$ per undulator. These are discovered by binary erosion, explained in the code below.

In [5]:
def _fetch_archiver_snapshot(pv_names, from_time, to_time):
    if isinstance(pv_names, str):
        pv_names = [pv_names]
    payload = meme.archive.get(pv_names, from_time=from_time, to_time=to_time)
    if len(pv_names) == 1:
        pv = pv_names[0]
        return {pv: (dt.fromtimestamp(payload['secondsPastEpoch'][-1]), payload['values'][-1])}
    else:
        # return payload[0]
        return {d['pvName']: (dt.fromtimestamp(d['value']['value']['secondsPastEpoch'][-1]), d['value']['value']['values'][-1]) for d in payload}

In [7]:
_fetch_archiver_snapshot(['BEND:DMPS:400:BACT'], from_time=end, to_time=end + snapshot_delta)

{'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 18, 31, 41),
  np.float64(4.999996396518345))}

### $\lambda_u$

In [8]:

# Discover all undulators
meme.names.list_pvs('USEG:UNDS:%:KAct')

2026-06-13T18:32:15.743768024 WARN pvxs.client.io Server 134.79.151.36:42467 no supported auth.  try to force 'anonymous'

['USEG:UNDS:2150:KAct',
 'USEG:UNDS:2250:KAct',
 'USEG:UNDS:2350:KAct',
 'USEG:UNDS:2450:KAct',
 'USEG:UNDS:2550:KAct',
 'USEG:UNDS:2650:KAct',
 'USEG:UNDS:2750:KAct',
 'USEG:UNDS:2850:KAct',
 'USEG:UNDS:2950:KAct',
 'USEG:UNDS:3050:KAct',
 'USEG:UNDS:3150:KAct',
 'USEG:UNDS:3250:KAct',
 'USEG:UNDS:3350:KAct',
 'USEG:UNDS:3450:KAct',
 'USEG:UNDS:3650:KAct',
 'USEG:UNDS:3750:KAct',
 'USEG:UNDS:3850:KAct',
 'USEG:UNDS:3950:KAct',
 'USEG:UNDS:4050:KAct',
 'USEG:UNDS:4150:KAct',
 'USEG:UNDS:4250:KAct',
 'USEG:UNDS:4350:KAct',
 'USEG:UNDS:4450:KAct',
 'USEG:UNDS:4550:KAct',
 'USEG:UNDS:4650:KAct',
 'USEG:UNDS:4750:KAct']

In [9]:
# Find the lambda_U field in the undulator PVs
meme.names.list_pvs('USEG:UNDS:4750:%')

2026-06-13T18:32:18.977315573 ERR pvxs.client.dup Duplicate PV name ds from 134.79.151.36:42467 and 134.79.151.21:34077
2026-06-13T18:32:18.977515810 WARN pvxs.client.io Server 134.79.151.36:42467 no supported auth.  try to force 'anonymous'

['USEG:UNDS:4750:ACKALL',
 'USEG:UNDS:4750:AD:STATSUMY',
 'USEG:UNDS:4750:AD:STATSUMYFP',
 'USEG:UNDS:4750:AG2KSpl:Check',
 'USEG:UNDS:4750:AG2KSpl:CheckStat',
 'USEG:UNDS:4750:AG2KSpl:DeltaKTemp',
 'USEG:UNDS:4750:AG2KSpl:InputTempCor',
 'USEG:UNDS:4750:AG2KSpl:Limits',
 'USEG:UNDS:4750:AG2KSpl:MaxGAP',
 'USEG:UNDS:4750:AG2KSpl:MaxK',
 'USEG:UNDS:4750:AG2KSpl:MinGAP',
 'USEG:UNDS:4750:AG2KSpl:MinK',
 'USEG:UNDS:4750:AG2KSpl:OutputTempCor',
 'USEG:UNDS:4750:AG2KSpl:TempIn',
 'USEG:UNDS:4750:AG2KSpl:TempOut',
 'USEG:UNDS:4750:AG2KSpl:Trans1',
 'USEG:UNDS:4750:AG2KSpl:Trans1Dir',
 'USEG:UNDS:4750:AG2KSpl:Trans1Name',
 'USEG:UNDS:4750:AUTOBRAKE',
 'USEG:UNDS:4750:Abort',
 'USEG:UNDS:4750:AbortState',
 'USEG:UNDS:4750:ActiveMode',
 'USEG:UNDS:4750:AlignmentOffset',
 'USEG:UNDS:4750:AlignmentSlope',
 'USEG:UNDS:4750:AlignmentTaper',
 'USEG:UNDS:4750:AllowUndCenter',
 'USEG:UNDS:4750:AuotofocusEnabledDbg',
 'USEG:UNDS:4750:AutoCommit',
 'USEG:UNDS:4750:CM:STATSUMY',
 'USEG:UNDS:4750:CM:STATSUMY1',
 'USEG:UNDS:4750:CM:STATSUMY2',
 'USEG:UNDS:4750:CM:STATSUMYFP',
 'USEG:UNDS:4750:CM:STATSUMYFP1',
 'USEG:UNDS:4750:CM:STATSUMYFP2',
 'USEG:UNDS:4750:CheckUndCentered',
 'USEG:UNDS:4750:Commit',
 'USEG:UNDS:4750:ConvertGap2K',
 'USEG:UNDS:4750:ConvertK2Gap',
 'USEG:UNDS:4750:CtrLnDeadband',
 'USEG:UNDS:4750:CtrLnDiffOffset',
 'USEG:UNDS:4750:CtrLnDiffSlope',
 'USEG:UNDS:4750:CtrLnGo',
 'USEG:UNDS:4750:CtrLnGoSQ',
 'USEG:UNDS:4750:CtrLnOffset',
 'USEG:UNDS:4750:CtrLnOffsetDP',
 'USEG:UNDS:4750:CtrLnOffsetFP',
 'USEG:UNDS:4750:CtrLnOffsetSV',
 'USEG:UNDS:4750:CtrLnSlope',
 'USEG:UNDS:4750:CtrLnSlopeDP',
 'USEG:UNDS:4750:CtrLnSlopeFP',
 'USEG:UNDS:4750:CtrLnSlopeSV',
 'USEG:UNDS:4750:DEBUGLEVEL',
 'USEG:UNDS:4750:DG2KSpl:Check',
 'USEG:UNDS:4750:DG2KSpl:CheckStat',
 'USEG:UNDS:4750:DG2KSpl:DeltaKTemp',
 'USEG:UNDS:4750:DG2KSpl:InputTempCor',
 'USEG:UNDS:4750:DG2KSpl:Limits',
 'USEG:UNDS:4750:DG2KSpl:MaxGAP',
 'USEG:UNDS:4750:DG2KSpl:MaxK',
 'USEG:UNDS:4750:DG2KSpl:MinGAP',
 'USEG:UNDS:4750:DG2KSpl:MinK',
 'USEG:UNDS:4750:DG2KSpl:OutputTempCor',
 'USEG:UNDS:4750:DG2KSpl:TempIn',
 'USEG:UNDS:4750:DG2KSpl:TempOut',
 'USEG:UNDS:4750:DG2KSpl:Trans1',
 'USEG:UNDS:4750:DG2KSpl:Trans1Dir',
 'USEG:UNDS:4750:DG2KSpl:Trans1Name',
 'USEG:UNDS:4750:DK2GSpl:Check',
 'USEG:UNDS:4750:DK2GSpl:CheckStat',
 'USEG:UNDS:4750:DK2GSpl:DeltaKTemp',
 'USEG:UNDS:4750:DK2GSpl:InputTempCor',
 'USEG:UNDS:4750:DK2GSpl:Limits',
 'USEG:UNDS:4750:DK2GSpl:MaxGAP',
 'USEG:UNDS:4750:DK2GSpl:MaxK',
 'USEG:UNDS:4750:DK2GSpl:MinGAP',
 'USEG:UNDS:4750:DK2GSpl:MinK',
 'USEG:UNDS:4750:DK2GSpl:OutputTempCor',
 'USEG:UNDS:4750:DK2GSpl:TempIn',
 'USEG:UNDS:4750:DK2GSpl:TempOut',
 'USEG:UNDS:4750:DK2GSpl:Trans0',
 'USEG:UNDS:4750:DK2GSpl:Trans0Dir',
 'USEG:UNDS:4750:DK2GSpl:Trans0Name',
 'USEG:UNDS:4750:DLY',
 'USEG:UNDS:4750:DLYCLC',
 'USEG:UNDS:4750:DLYINPUT',
 'USEG:UNDS:4750:DS:AlignmentEncRbck',
 'USEG:UNDS:4750:DS:AlignmentQuadY',
 'USEG:UNDS:4750:DS:CtrLnShift',
 'USEG:UNDS:4750:DS:EncRbck',
 'USEG:UNDS:4750:DS:EncZero',
 'USEG:UNDS:4750:DS:GapRef',
 'USEG:UNDS:4750:DS:PitchCorFactor',
 'USEG:UNDS:4750:DS:PotExtensionAct',
 'USEG:UNDS:4750:DS:PotOffset',
 'USEG:UNDS:4750:DS:PotSlope',
 'USEG:UNDS:4750:DS:PotVRef',
 'USEG:UNDS:4750:DS:SetEncoder',
 'USEG:UNDS:4750:DS:VAct',
 'USEG:UNDS:4750:DS:VDes',
 'USEG:UNDS:4750:DSG2KSpl:Check',
 'USEG:UNDS:4750:DSG2KSpl:CheckStat',
 'USEG:UNDS:4750:DSG2KSpl:DeltaKTemp',
 'USEG:UNDS:4750:DSG2KSpl:InputTempCor',
 'USEG:UNDS:4750:DSG2KSpl:Limits',
 'USEG:UNDS:4750:DSG2KSpl:MaxGAP',
 'USEG:UNDS:4750:DSG2KSpl:MaxK',
 'USEG:UNDS:4750:DSG2KSpl:MinGAP',
 'USEG:UNDS:4750:DSG2KSpl:MinK',
 'USEG:UNDS:4750:DSG2KSpl:OutputTempCor',
 'USEG:UNDS:4750:DSG2KSpl:TempIn',
 'USEG:UNDS:4750:DSG2KSpl:TempOut',
 'USEG:UNDS:4750:DSG2KSpl:Trans1',
 'USEG:UNDS:4750:DSG2KSpl:Trans1Dir',
 'USEG:UNDS:4750:DSG2KSpl:Trans1Name',
 'USEG:UNDS:4750:DSKAct',
 'USEG:UNDS:4750:DSNEGY:EncOffset',
 'USEG:UNDS:4750:DSNEGY:EncOffsetRbck',
 'USEG:UNDS:4750:DSNEGY:EncOffsetRbckPrev',
 'USEG:UNDS:4750:DSNEGY:Fault',
 'USEG:UNDS:4750:DSNEGY:FaultDP',
 'USEG:UNDS:4750:DSNEGY:FaultFP',
 'USEG:UNDS:4750:DSNEGY:FaultSV',
 'USEG:UNDS:4750:DSNEGY:Keep',
 'USEG:UNDS:4750:DSNEGY:Motr',
 'USEG:UNDS:4750:DSNEGY:MotrCOMERStatus',
 'USEG:UNDS:4750:DSNEGY:MotrErrorCalc',
 'USEG:UNDS:4750:DSNEGY:MotrHLSStatus',
 'USEG:UNDS:4750:DSNEGY:MotrHOMEDStatus',
 'USEG:UNDS:4750:DSNEGY:MotrLLSStatus',
 'USEG:UNDS:4750:DSNEGY:MotrPROBStatus',
 'USEG:UNDS:4750:DSNEGY:Status',
 'USEG:UNDS:4750:DSNEGY:StatusCalc',
 'USEG:UNDS:4750:DSNEGY:StatusHB',
 'USEG:UNDS:4750:DSNEGY:StatusLB',
 'USEG:UNDS:4750:DSPOSY:AutofocusStatus',
 'USEG:UNDS:4750:DSPOSY:EncOffset',
 'USEG:UNDS:4750:DSPOSY:EncOffsetRbck',
 'USEG:UNDS:4750:DSPOSY:EncOffsetRbckPrev',
 'USEG:UNDS:4750:DSPOSY:Fault',
 'USEG:UNDS:4750:DSPOSY:FaultDP',
 'USEG:UNDS:4750:DSPOSY:FaultFP',
 'USEG:UNDS:4750:DSPOSY:FaultSV',
 'USEG:UNDS:4750:DSPOSY:Keep',
 'USEG:UNDS:4750:DSPOSY:Motr',
 'USEG:UNDS:4750:DSPOSY:MotrCOMERStatus',
 'USEG:UNDS:4750:DSPOSY:MotrErrorCalc',
 'USEG:UNDS:4750:DSPOSY:MotrHLSStatus',
 'USEG:UNDS:4750:DSPOSY:MotrHOMEDStatus',
 'USEG:UNDS:4750:DSPOSY:MotrLLSStatus',
 'USEG:UNDS:4750:DSPOSY:MotrPROBStatus',
 'USEG:UNDS:4750:DSPOSY:Status',
 'USEG:UNDS:4750:DSPOSY:StatusCalc',
 'USEG:UNDS:4750:DSPOSY:StatusHB',
 'USEG:UNDS:4750:DSPOSY:StatusLB',
 'USEG:UNDS:4750:Deadband',
 'USEG:UNDS:4750:DeltaTemp',
 'USEG:UNDS:4750:ElapsedTime',
 'USEG:UNDS:4750:EncOffsetStatus',
 'USEG:UNDS:4750:ExecMessage',
 'USEG:UNDS:4750:ExecState',
 'USEG:UNDS:4750:ExecStatus',
 'USEG:UNDS:4750:GapAct',
 'USEG:UNDS:4750:GapActDP',
 'USEG:UNDS:4750:GapActFP',
 'USEG:UNDS:4750:GapActSV',
 'USEG:UNDS:4750:GapDes',
 'USEG:UNDS:4750:GapDmov',
 'USEG:UNDS:4750:GapKeep',
 'USEG:UNDS:4750:GetParam',
 'USEG:UNDS:4750:GetParamRbck',
 'USEG:UNDS:4750:Go',
 'USEG:UNDS:4750:KADErr',
 'USEG:UNDS:4750:KAct',
 'USEG:UNDS:4750:KDes',
 'USEG:UNDS:4750:KTempCoeff',
 'USEG:UNDS:4750:MMFTemp',
 'USEG:UNDS:4750:MOTOR:ASYN',
 'USEG:UNDS:4750:MaintenanceM',
 'USEG:UNDS:4750:MaxRetries',
 'USEG:UNDS:4750:MeanTemp',
 'USEG:UNDS:4750:MeanTempDP',
 'USEG:UNDS:4750:MeanTempFP',
 'USEG:UNDS:4750:MeanTempSV',
 'USEG:UNDS:4750:MoveFraction',
 'USEG:UNDS:4750:MoveVelo',
 'USEG:UNDS:4750:NEGYJAW:CheckEnabled',
 'USEG:UNDS:4750:NEGYJAW:Disable',
 'USEG:UNDS:4750:NEGYJAW:Enable',
 'USEG:UNDS:4750:NEGYJAW:EnableStatus',
 'USEG:UNDS:4750:NEGYJAW:MoveInc',
 'USEG:UNDS:4750:OffsetAct',
 'USEG:UNDS:4750:OffsetActDP',
 'USEG:UNDS:4750:OffsetActFP',
 'USEG:UNDS:4750:OffsetActSV',
 'USEG:UNDS:4750:OffsetDes',
 'USEG:UNDS:4750:OffsetDesPrev',
 'USEG:UNDS:4750:OffsetKeep',
 'USEG:UNDS:4750:POSYJAW:CheckEnabled',
 'USEG:UNDS:4750:POSYJAW:Disable',
 'USEG:UNDS:4750:POSYJAW:Enable',
 'USEG:UNDS:4750:POSYJAW:EnableStatus',
 'USEG:UNDS:4750:POSYJAW:MoveInc',
 'USEG:UNDS:4750:PwrLSStatus',
 'USEG:UNDS:4750:RESET',
 'USEG:UNDS:4750:RESETBitWrt',
 'USEG:UNDS:4750:ReadEncOffsets',
 'USEG:UNDS:4750:RestAlignSetpt',
 'USEG:UNDS:4750:RestAlignSetptSQ',
 'USEG:UNDS:4750:RestoreEncOffsets',
 'USEG:UNDS:4750:Retries',
 'USEG:UNDS:4750:SIMMODE',
 'USEG:UNDS:4750:SNGLAPPRCH',
 'USEG:UNDS:4750:STATSUMY',
 'USEG:UNDS:4750:STATSUMYFP',
 'USEG:UNDS:4750:SerialNum',
 'USEG:UNDS:4750:SetEncOffsets',
 'USEG:UNDS:4750:SetGapState',
 'USEG:UNDS:4750:SetParam',
 'USEG:UNDS:4750:SlopeAct',
 'USEG:UNDS:4750:SlopeActDP',
 'USEG:UNDS:4750:SlopeActFP',
 'USEG:UNDS:4750:SlopeActSV',
 'USEG:UNDS:4750:SlopeDes',
 'USEG:UNDS:4750:SlopeDesPrev',
 'USEG:UNDS:4750:SlopeKeep',
 'USEG:UNDS:4750:Stop',
 'USEG:UNDS:4750:TaperAct',
 'USEG:UNDS:4750:TaperActDP',
 'USEG:UNDS:4750:TaperActFP',
 'USEG:UNDS:4750:TaperActSV',
 'USEG:UNDS:4750:TaperDes',
 'USEG:UNDS:4750:TaperKeep',
 'USEG:UNDS:4750:Task1Status',
 'USEG:UNDS:4750:Task2Status',
 'USEG:UNDS:4750:Task3Status',
 'USEG:UNDS:4750:Task4Status',
 'USEG:UNDS:4750:Task5Status',
 'USEG:UNDS:4750:Temp01',
 'USEG:UNDS:4750:Temp01_AVG',
 'USEG:UNDS:4750:Temp01_DATA',
 'USEG:UNDS:4750:Temp02',
 'USEG:UNDS:4750:Temp02_AVG',
 'USEG:UNDS:4750:Temp02_DATA',
 'USEG:UNDS:4750:Temp03',
 'USEG:UNDS:4750:Temp03_AVG',
 'USEG:UNDS:4750:Temp03_DATA',
 'USEG:UNDS:4750:Temp04',
 'USEG:UNDS:4750:Temp04_AVG',
 'USEG:UNDS:4750:Temp04_DATA',
 'USEG:UNDS:4750:Temp05',
 'USEG:UNDS:4750:Temp05_AVG',
 'USEG:UNDS:4750:Temp05_DATA',
 'USEG:UNDS:4750:Temp06',
 'USEG:UNDS:4750:Temp06_AVG',
 'USEG:UNDS:4750:Temp06_DATA',
 'USEG:UNDS:4750:Temp07',
 'USEG:UNDS:4750:Temp07_AVG',
 'USEG:UNDS:4750:Temp07_DATA',
 'USEG:UNDS:4750:Temp08',
 'USEG:UNDS:4750:Temp08_AVG',
 'USEG:UNDS:4750:Temp08_DATA',
 'USEG:UNDS:4750:TempAIncludeReq',
 'USEG:UNDS:4750:TempAIncludeStat',
 'USEG:UNDS:4750:TempAdjust',
 'USEG:UNDS:4750:TempAdjustCalc',
 'USEG:UNDS:4750:TempAdjustCount',
 'USEG:UNDS:4750:TempAdjustDbg',
 'USEG:UNDS:4750:TempAdjustStat',
 'USEG:UNDS:4750:TempAdjustStatDP',
 'USEG:UNDS:4750:TempAdjustStatFP',
 'USEG:UNDS:4750:TempAdjustStatSV',
 'USEG:UNDS:4750:TempBIncludeReq',
 'USEG:UNDS:4750:TempBIncludeStat',
 'USEG:UNDS:4750:TempCIncludeReq',
 'USEG:UNDS:4750:TempCIncludeStat',
 'USEG:UNDS:4750:TempDIncludeReq',
 'USEG:UNDS:4750:TempDIncludeStat',
 'USEG:UNDS:4750:TempSpread',
 'USEG:UNDS:4750:TiltLSStatus',
 'USEG:UNDS:4750:TriggerHWRst',
 'USEG:UNDS:4750:US:AlignmentEncRbck',
 'USEG:UNDS:4750:US:AlignmentQuadY',
 'USEG:UNDS:4750:US:CtrLnShift',
 'USEG:UNDS:4750:US:EncRbck',
 'USEG:UNDS:4750:US:EncZero',
 'USEG:UNDS:4750:US:GapRef',
 'USEG:UNDS:4750:US:PitchCorFactor',
 'USEG:UNDS:4750:US:PotExtensionAct',
 'USEG:UNDS:4750:US:PotOffset',
 'USEG:UNDS:4750:US:PotSlope',
 'USEG:UNDS:4750:US:PotVRef',
 'USEG:UNDS:4750:US:SetEncoder',
 'USEG:UNDS:4750:US:VAct',
 'USEG:UNDS:4750:US:VDes',
 'USEG:UNDS:4750:USNEGY:EncOffset',
 'USEG:UNDS:4750:USNEGY:EncOffsetRbck',
 'USEG:UNDS:4750:USNEGY:EncOffsetRbckPrev',
 'USEG:UNDS:4750:USNEGY:Fault',
 'USEG:UNDS:4750:USNEGY:FaultDP',
 'USEG:UNDS:4750:USNEGY:FaultFP',
 'USEG:UNDS:4750:USNEGY:FaultSV',
 'USEG:UNDS:4750:USNEGY:Keep',
 'USEG:UNDS:4750:USNEGY:Motr',
 'USEG:UNDS:4750:USNEGY:MotrCOMERStatus',
 'USEG:UNDS:4750:USNEGY:MotrErrorCalc',
 'USEG:UNDS:4750:USNEGY:MotrHLSStatus',
 'USEG:UNDS:4750:USNEGY:MotrHOMEDStatus',
 'USEG:UNDS:4750:USNEGY:MotrLLSStatus',
 'USEG:UNDS:4750:USNEGY:MotrPROBStatus',
 'USEG:UNDS:4750:USNEGY:Status',
 'USEG:UNDS:4750:USNEGY:StatusCalc',
 'USEG:UNDS:4750:USNEGY:StatusHB',
 'USEG:UNDS:4750:USNEGY:StatusLB',
 'USEG:UNDS:4750:USPOSY:AutofocusStatus',
 'USEG:UNDS:4750:USPOSY:EncOffset',
 'USEG:UNDS:4750:USPOSY:EncOffsetRbck',
 'USEG:UNDS:4750:USPOSY:EncOffsetRbckPrev',
 'USEG:UNDS:4750:USPOSY:Fault',
 'USEG:UNDS:4750:USPOSY:FaultDP',
 'USEG:UNDS:4750:USPOSY:FaultFP',
 'USEG:UNDS:4750:USPOSY:FaultSV',
 'USEG:UNDS:4750:USPOSY:Keep',
 'USEG:UNDS:4750:USPOSY:Motr',
 'USEG:UNDS:4750:USPOSY:MotrCOMERStatus',
 'USEG:UNDS:4750:USPOSY:MotrErrorCalc',
 'USEG:UNDS:4750:USPOSY:MotrHLSStatus',
 'USEG:UNDS:4750:USPOSY:MotrHOMEDStatus',
 'USEG:UNDS:4750:USPOSY:MotrLLSStatus',
 'USEG:UNDS:4750:USPOSY:MotrPROBStatus',
 'USEG:UNDS:4750:USPOSY:Status',
 'USEG:UNDS:4750:USPOSY:StatusCalc',
 'USEG:UNDS:4750:USPOSY:StatusHB',
 'USEG:UNDS:4750:USPOSY:StatusLB',
 'USEG:UNDS:4750:UndCentered',
 'USEG:UNDS:4750:UndulatorError',
 'USEG:UNDS:4750:VCCenterDis',
 'USEG:UNDS:4750:VCCenterDis1',
 'USEG:UNDS:4750:VCCenterDis2',
 'USEG:UNDS:4750:VCCenterDis3',
 'USEG:UNDS:4750:VCCenterDis4',
 'USEG:UNDS:4750:VCLSStatus',
 'USEG:UNDS:4750:VCOffsetCorFactor',
 'USEG:UNDS:4750:VCSlopeCorFactor',
 'USEG:UNDS:4750:VCTDisable',
 'USEG:UNDS:4750:VCTGo',
 'USEG:UNDS:4750:VCTState',
 'USEG:UNDS:4750:VCTStop',
 'USEG:UNDS:4750:VCTaperCorFactor',
 'USEG:UNDS:4750:lambda_U']

In [10]:
# Discover all undulator periods
lambda_u_pvs = meme.names.list_pvs('USEG:UNDS:%:lambda_U')
lambda_u_dict = {}
for pv in lambda_u_pvs:
    payload = meme.archive.get(pv)
    lambda_u_dict[pv] = payload['values']
    print(pv, payload)

USEG:UNDS:2150:lambda_U {'secondsPastEpoch': array([], dtype=float64), 'values': array([], dtype=float64), 'nanoseconds': array([], dtype=float64), 'severity': array([], dtype=float64), 'status': array([], dtype=float64)}
USEG:UNDS:2250:lambda_U {'secondsPastEpoch': array([], dtype=float64), 'values': array([], dtype=float64), 'nanoseconds': array([], dtype=float64), 'severity': array([], dtype=float64), 'status': array([], dtype=float64)}
USEG:UNDS:2350:lambda_U {'secondsPastEpoch': array([], dtype=float64), 'values': array([], dtype=float64), 'nanoseconds': array([], dtype=float64), 'severity': array([], dtype=float64), 'status': array([], dtype=float64)}
USEG:UNDS:2450:lambda_U {'secondsPastEpoch': array([], dtype=float64), 'values': array([], dtype=float64), 'nanoseconds': array([], dtype=float64), 'severity': array([], dtype=float64), 'status': array([], dtype=float64)}
USEG:UNDS:2550:lambda_U {'secondsPastEpoch': array([], dtype=float64), 'values': array([], dtype=float64), 'nanoseconds': array([], dtype=float64), 'severity': array([], dtype=float64), 'status': array([], dtype=float64)}
USEG:UNDS:2650:lambda_U {'secondsPastEpoch': array([1744678631]), 'values': array([0.056]), 'nanoseconds': array([58538817]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:2750:lambda_U {'secondsPastEpoch': array([1747100473]), 'values': array([0.056]), 'nanoseconds': array([658443519]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:2850:lambda_U {'secondsPastEpoch': array([1749594483]), 'values': array([0.056]), 'nanoseconds': array([192107261]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:2950:lambda_U {'secondsPastEpoch': array([1753928971]), 'values': array([0.056]), 'nanoseconds': array([280892926]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3050:lambda_U {'secondsPastEpoch': array([1753928959]), 'values': array([0.056]), 'nanoseconds': array([360356391]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3150:lambda_U {'secondsPastEpoch': array([1753407501]), 'values': array([0.056]), 'nanoseconds': array([281249016]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3250:lambda_U {'secondsPastEpoch': array([1753407505]), 'values': array([0.056]), 'nanoseconds': array([620073748]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3350:lambda_U {'secondsPastEpoch': array([1758574987]), 'values': array([0.056]), 'nanoseconds': array([759594079]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3450:lambda_U {'secondsPastEpoch': array([1760995472]), 'values': array([0.056]), 'nanoseconds': array([623811456]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3650:lambda_U {'secondsPastEpoch': array([1763426990]), 'values': array([0.056]), 'nanoseconds': array([676425537]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3750:lambda_U {'secondsPastEpoch': array([1766021166]), 'values': array([0.056]), 'nanoseconds': array([56809663]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3850:lambda_U {'secondsPastEpoch': array([1766021169]), 'values': array([0.056]), 'nanoseconds': array([692769092]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:3950:lambda_U {'secondsPastEpoch': array([1770682534]), 'values': array([0.056]), 'nanoseconds': array([910493011]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4050:lambda_U {'secondsPastEpoch': array([1775605698]), 'values': array([0.056]), 'nanoseconds': array([708279453]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4150:lambda_U {'secondsPastEpoch': array([1777935053]), 'values': array([0.056]), 'nanoseconds': array([922285002]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4250:lambda_U {'secondsPastEpoch': array([1780348051]), 'values': array([0.056]), 'nanoseconds': array([332998901]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4350:lambda_U {'secondsPastEpoch': array([1741134271]), 'values': array([0.039]), 'nanoseconds': array([407207269]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4450:lambda_U {'secondsPastEpoch': array([1741134271]), 'values': array([0.039]), 'nanoseconds': array([407337374]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4550:lambda_U {'secondsPastEpoch': array([1741134271]), 'values': array([0.039]), 'nanoseconds': array([407475097]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4650:lambda_U {'secondsPastEpoch': array([1741134271]), 'values': array([0.039]), 'nanoseconds': array([407632353]), 'severity': array([0]), 'status': array([0])}
USEG:UNDS:4750:lambda_U {'secondsPastEpoch': array([1741134271]), 'values': array([0.039]), 'nanoseconds': array([407769891]), 'severity': array([0]), 'status': array([0])}

In [11]:
lambda_u_dict

{'USEG:UNDS:2150:lambda_U': array([], dtype=float64),
 'USEG:UNDS:2250:lambda_U': array([], dtype=float64),
 'USEG:UNDS:2350:lambda_U': array([], dtype=float64),
 'USEG:UNDS:2450:lambda_U': array([], dtype=float64),
 'USEG:UNDS:2550:lambda_U': array([], dtype=float64),
 'USEG:UNDS:2650:lambda_U': array([0.056]),
 'USEG:UNDS:2750:lambda_U': array([0.056]),
 'USEG:UNDS:2850:lambda_U': array([0.056]),
 'USEG:UNDS:2950:lambda_U': array([0.056]),
 'USEG:UNDS:3050:lambda_U': array([0.056]),
 'USEG:UNDS:3150:lambda_U': array([0.056]),
 'USEG:UNDS:3250:lambda_U': array([0.056]),
 'USEG:UNDS:3350:lambda_U': array([0.056]),
 'USEG:UNDS:3450:lambda_U': array([0.056]),
 'USEG:UNDS:3650:lambda_U': array([0.056]),
 'USEG:UNDS:3750:lambda_U': array([0.056]),
 'USEG:UNDS:3850:lambda_U': array([0.056]),
 'USEG:UNDS:3950:lambda_U': array([0.056]),
 'USEG:UNDS:4050:lambda_U': array([0.056]),
 'USEG:UNDS:4150:lambda_U': array([0.056]),
 'USEG:UNDS:4250:lambda_U': array([0.056]),
 'USEG:UNDS:4350:lambda_U': array([0.039]),
 'USEG:UNDS:4450:lambda_U': array([0.039]),
 'USEG:UNDS:4550:lambda_U': array([0.039]),
 'USEG:UNDS:4650:lambda_U': array([0.039]),
 'USEG:UNDS:4750:lambda_U': array([0.039])}

For some reason $\lambda_u$ is not archived for some undulators, so we use a cheeky `caget` just to be safe:

In [13]:
for pv in lambda_u_pvs:
    os.system(f'caget {pv}')

USEG:UNDS:2150:lambda_U        0.056
USEG:UNDS:2250:lambda_U        0.056
USEG:UNDS:2350:lambda_U        0.056
USEG:UNDS:2450:lambda_U        0.056
USEG:UNDS:2550:lambda_U        0.056
USEG:UNDS:2650:lambda_U        0.056
USEG:UNDS:2750:lambda_U        0.056
USEG:UNDS:2850:lambda_U        0.056
USEG:UNDS:2950:lambda_U        0.056
USEG:UNDS:3050:lambda_U        0.056
USEG:UNDS:3150:lambda_U        0.056
USEG:UNDS:3250:lambda_U        0.056
USEG:UNDS:3350:lambda_U        0.056
USEG:UNDS:3450:lambda_U        0.056
USEG:UNDS:3650:lambda_U        0.056
USEG:UNDS:3750:lambda_U        0.056
USEG:UNDS:3850:lambda_U        0.056
USEG:UNDS:3950:lambda_U        0.056
USEG:UNDS:4050:lambda_U        0.056
USEG:UNDS:4150:lambda_U        0.056
USEG:UNDS:4250:lambda_U        0.056
USEG:UNDS:4350:lambda_U        0.039
USEG:UNDS:4450:lambda_U        0.039
USEG:UNDS:4550:lambda_U        0.039
USEG:UNDS:4650:lambda_U        0.039
USEG:UNDS:4750:lambda_U        0.039

In [14]:
# Use caget to populate the lambda_u_dict with the current values
for pv in lambda_u_pvs:
    value = os.popen(f'caget {pv}').read().strip()
    value = float(re.search(r'[0-9.-]+$', value).group()) # Find a decimal number at the end of the string
    lambda_u_dict[pv] = value

In [15]:
# Fully populated thanks to caget
lambda_u_dict

{'USEG:UNDS:2150:lambda_U': 0.056,
 'USEG:UNDS:2250:lambda_U': 0.056,
 'USEG:UNDS:2350:lambda_U': 0.056,
 'USEG:UNDS:2450:lambda_U': 0.056,
 'USEG:UNDS:2550:lambda_U': 0.056,
 'USEG:UNDS:2650:lambda_U': 0.056,
 'USEG:UNDS:2750:lambda_U': 0.056,
 'USEG:UNDS:2850:lambda_U': 0.056,
 'USEG:UNDS:2950:lambda_U': 0.056,
 'USEG:UNDS:3050:lambda_U': 0.056,
 'USEG:UNDS:3150:lambda_U': 0.056,
 'USEG:UNDS:3250:lambda_U': 0.056,
 'USEG:UNDS:3350:lambda_U': 0.056,
 'USEG:UNDS:3450:lambda_U': 0.056,
 'USEG:UNDS:3650:lambda_U': 0.056,
 'USEG:UNDS:3750:lambda_U': 0.056,
 'USEG:UNDS:3850:lambda_U': 0.056,
 'USEG:UNDS:3950:lambda_U': 0.056,
 'USEG:UNDS:4050:lambda_U': 0.056,
 'USEG:UNDS:4150:lambda_U': 0.056,
 'USEG:UNDS:4250:lambda_U': 0.056,
 'USEG:UNDS:4350:lambda_U': 0.039,
 'USEG:UNDS:4450:lambda_U': 0.039,
 'USEG:UNDS:4550:lambda_U': 0.039,
 'USEG:UNDS:4650:lambda_U': 0.039,
 'USEG:UNDS:4750:lambda_U': 0.039}

### $\gamma$

In [16]:
# Runtime: around 10s for 10 days of data at 4h intervals, with 3s snapshots

gamma_snapshots = []
t = start
while t < end:
    snapshot = _fetch_archiver_snapshot('BEND:DMPS:400:BACT', from_time=t, to_time=t + snapshot_delta)
    gamma_snapshots.append(snapshot)
    t += coarse_delta

In [17]:
gamma_snapshots

[{'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(10.000011194073167))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 4, 0, 1),
   np.float64(9.999996080362873))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(9.999997371432526))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(10.000004732854245))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 16, 0, 2),
   np.float64(9.999996898116873))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 1, 20, 0, 2),
   np.float64(10.000006359602438))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(10.000002237982937))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 4, 0, 1),
   np.float64(10.000000932995325))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 8, 0, 2),
   np.float64(9.999993393100754))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 12, 0, 2),
   np.float64(9.9999969839699))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 16, 0, 1),
   np.float64(9.999998560069184))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 2, 20, 0, 2),
   np.float64(9.999999733716557))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 0, 0, 2),
   np.float64(10.000005736774783))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 4, 0, 2),
   np.float64(9.999996744411284))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 8, 0, 2),
   np.float64(10.000005808051865))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 12, 0, 1),
   np.float64(10.000001143518885))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 16, 0, 2),
   np.float64(9.999998774604546))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 3, 20, 0, 2),
   np.float64(9.99999763467151))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 0, 0, 1),
   np.float64(9.999995840213423))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 4, 0, 2),
   np.float64(10.000000127296342))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 8, 0, 1),
   np.float64(9.999996568661874))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 12, 0, 2),
   np.float64(9.999992796307989))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 16, 0, 2),
   np.float64(10.000002186202796))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 4, 20, 0, 2),
   np.float64(9.999991667948805))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 0, 0, 1),
   np.float64(10.000002261384111))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 4, 0, 2),
   np.float64(10.000004875732099))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 8, 0, 2),
   np.float64(9.99999760738451))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 12, 0, 1),
   np.float64(10.00000202185051))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 16, 0, 2),
   np.float64(9.999998314748431))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 5, 20, 0, 2),
   np.float64(10.000003329126818))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 0, 0, 2),
   np.float64(10.000006012043503))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 4, 0, 2),
   np.float64(10.00000482621041))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 8, 0, 2),
   np.float64(9.99999388610727))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 12, 0, 1),
   np.float64(10.000002199062406))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 16, 0, 2),
   np.float64(10.000006527519359))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 6, 20, 0, 2),
   np.float64(10.000004475884866))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 0, 0, 2),
   np.float64(9.999999166887127))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 4, 0, 2),
   np.float64(10.000006429717729))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 8, 0, 2),
   np.float64(9.999995864635594))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 12, 0),
   np.float64(9.999998916287613))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 16, 0, 2),
   np.float64(9.99999929726394))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 7, 20, 0, 2),
   np.float64(10.00000332648885))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 0, 0, 2),
   np.float64(10.000001713917213))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 4, 0, 2),
   np.float64(9.999995579105718))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 8, 0, 2),
   np.float64(9.999998948972724))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 12, 0, 2),
   np.float64(9.99999566754936))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 16, 0, 2),
   np.float64(9.999999537910979))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 8, 20, 0, 1),
   np.float64(9.999992975549986))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 0, 0, 2),
   np.float64(9.99999409371624))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 4, 0, 2),
   np.float64(9.99999444898331))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 8, 0, 2),
   np.float64(9.999996928576483))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 12, 0, 2),
   np.float64(10.000002446608704))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 16, 0, 2),
   np.float64(9.999999471776896))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 9, 20, 0, 2),
   np.float64(3.999995441333942))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 0, 0, 1),
   np.float64(3.999997438669841))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 4, 0, 2),
   np.float64(4.000000048550793))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 8, 0, 2),
   np.float64(4.000001854498162))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 12, 0, 2),
   np.float64(3.999997835430039))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 16, 0, 2),
   np.float64(3.9999977822683315))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 10, 20, 0, 2),
   np.float64(4.000004782265255))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 0, 0, 2),
   np.float64(4.000004636718865))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 4, 0, 2),
   np.float64(3.9999964804820913))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 8, 0, 1),
   np.float64(3.9999961387693146))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 12, 0, 2),
   np.float64(4.000003574760206))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 16, 0, 2),
   np.float64(4.000003993292031))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 11, 20, 0, 2),
   np.float64(3.999987984617214))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 0, 0, 2),
   np.float64(4.000007095342181))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 4, 0, 2),
   np.float64(3.9999995167862545))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 8, 0, 2),
   np.float64(3.9999988862024973))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 12, 0, 2),
   np.float64(4.000007937249128))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 16, 0, 2),
   np.float64(4.000006749038301))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 12, 20, 0, 2),
   np.float64(4.000009522282116))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 0, 0, 2),
   np.float64(7.999991930875322))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 4, 0, 2),
   np.float64(7.999999709441514))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 8, 0, 2),
   np.float64(4.999995123100267))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 12, 0, 2),
   np.float64(5.000005369806373))},
 {'BEND:DMPS:400:BACT': (datetime.datetime(2026, 6, 13, 16, 0, 2),
   np.float64(5.000001802109856))}]

### $K$

In [18]:
# This takes about a minute to pull data for 10 days. We will maintain a cache in a CSV file so we don't have to do this every time.



k_archive = {}
und_nums = [re.search(r'USEG:UNDS:(\d+):lambda_U', pv).group(1) for pv in lambda_u_pvs]
kact_pvs = [f'USEG:UNDS:{num}:KAct' for num in und_nums]
k_snapshots = []
t = start
while t < end:
    snapshot = _fetch_archiver_snapshot(kact_pvs, from_time=t, to_time=t + snapshot_delta)
    k_snapshots.append(snapshot)
    t += coarse_delta

# Update the cache CSV file with the new snapshots
with open('k_snapshots.csv', 'w') as f:
    f.write('timestamp,value\n')
    for snapshot in gamma_snapshots:
        for pv, (timestamp, value) in snapshot.items():
            f.write(f'{timestamp},{value}\n')

In [19]:
k_snapshots

[{'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.725062129133953)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 0, 0),
   np.float64(6.72696357135488)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 56),
   np.float64(6.726536693442391)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.724772491594098)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 36),
   np.float64(6.724057586925176)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.7249611294244485)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.724410226463157)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 59),
   np.float64(6.724680969380071)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 0, 0),
   np.float64(6.7243741335124305)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 51),
   np.float64(6.724943444939528)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.724673599169667)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.7245965147312985)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.724864186865561)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 53),
   np.float64(6.724085817114299)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 54),
   np.float64(6.724638705950733)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 32),
   np.float64(6.722934632696281)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 52),
   np.float64(6.718377150579751)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(6.715974499691505)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 5, 31, 23, 58, 57),
   np.float64(6.711830236040759)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 35),
   np.float64(6.704956143228486)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(1.3725939148473192)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 57),
   np.float64(1.8003883026660679)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 56),
   np.float64(1.3215340152540307)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 0, 0, 2),
   np.float64(1.7067959351103383)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 5, 31, 23, 59, 48),
   np.float64(1.7535477305722151)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 0, 0),
   np.float64(1.6087383030836344))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 51),
   np.float64(6.7250476130802825)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 56),
   np.float64(6.727050458346672)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 1),
   np.float64(6.726618261462791)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 54),
   np.float64(6.724771638062182)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 51),
   np.float64(6.724006870827356)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 54),
   np.float64(6.725004690330177)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.724353123990159)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.724655557976247)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 58),
   np.float64(6.72437706499406)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 57),
   np.float64(6.7249379985397155)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 55),
   np.float64(6.724592900047611)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 48),
   np.float64(6.724581178256374)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 57),
   np.float64(6.724880526560553)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.724088645185826)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.72466674158056)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.723016994570205)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 59),
   np.float64(6.718458688407363)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 4, 0),
   np.float64(6.71606209656398)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.711891672233164)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 2),
   np.float64(6.70503739994378)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 4, 0, 1),
   np.float64(1.3725948384810847)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 57),
   np.float64(1.8003820779345094)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 4, 0),
   np.float64(1.3215192758991878)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 53),
   np.float64(1.7067900820370423)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 50),
   np.float64(1.7535380142076202)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 3, 59, 16),
   np.float64(1.6087353619030036))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(6.725296503823215)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 57),
   np.float64(6.727508820938772)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 45),
   np.float64(6.727144117830185)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 1),
   np.float64(6.72513449313974)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 59),
   np.float64(6.724268363134812)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 47),
   np.float64(6.725200107795923)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(6.72430200677161)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 1),
   np.float64(6.724813520069272)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 1),
   np.float64(6.724317308022319)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 1, 8, 0),
   np.float64(6.7252210711025056)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 48),
   np.float64(6.724886216670115)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 57),
   np.float64(6.724694227384599)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(6.725194247126628)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(6.7244076715868895)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 39),
   np.float64(6.725235010120951)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 55),
   np.float64(6.723573780593947)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 1),
   np.float64(6.718901855494921)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 48),
   np.float64(6.716551246566274)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 30),
   np.float64(6.7123239960660595)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 7, 58, 54),
   np.float64(6.705562725940436)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 2),
   np.float64(9.353407211641506e-06)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 45),
   np.float64(1.8005062001345313)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 58),
   np.float64(1.3215934473628468)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 7, 59, 10),
   np.float64(1.707004088930522)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 8, 0, 1),
   np.float64(1.75361891255077)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 8, 0),
   np.float64(1.6088074333334603))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 55),
   np.float64(6.7252270522664075)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(6.727591101559093)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(6.727216601343682)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 1),
   np.float64(6.725078439085388)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 53),
   np.float64(6.724148985664659)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 57),
   np.float64(6.7251353535902085)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 44),
   np.float64(6.724231306522048)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(6.72472279397223)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(6.724106036989672)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 1, 12, 0),
   np.float64(6.725037747985918)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 31),
   np.float64(6.724839194356567)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 55),
   np.float64(6.72467516815396)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 1),
   np.float64(6.725135010192916)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 1, 12, 0),
   np.float64(6.72436097606671)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 44),
   np.float64(6.725509444394343)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 58),
   np.float64(6.723826726729425)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 55),
   np.float64(6.719045339951934)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 12, 0),
   np.float64(6.716647086289951)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 1),
   np.float64(6.712492059042867)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 1),
   np.float64(6.705935612963054)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 8, 6, 29),
   np.float64(9.353335876496106e-06)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 2),
   np.float64(1.8005447915876718)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 12, 0, 1),
   np.float64(1.321634713607254)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 52),
   np.float64(1.7070441200126971)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 11, 58, 45),
   np.float64(1.7536886255901518)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 11, 59, 47),
   np.float64(1.6088523501109098))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 34),
   np.float64(6.7250101500548825)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 53),
   np.float64(6.727479050255515)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 55),
   np.float64(6.7270856156033485)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 55),
   np.float64(6.724912201240536)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 53),
   np.float64(6.723982724647359)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 2),
   np.float64(6.7250286465928)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 57),
   np.float64(6.7240339771615645)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 2),
   np.float64(6.724583444363444)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 16, 0),
   np.float64(6.723920305106382)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 38),
   np.float64(6.7248339176719965)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 1),
   np.float64(6.724726512874329)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 1),
   np.float64(6.724501710204618)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 2),
   np.float64(6.725025361552325)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 35),
   np.float64(6.724248936314033)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 58),
   np.float64(6.725319601224684)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 2),
   np.float64(6.723647577596614)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 1, 16, 0, 1),
   np.float64(6.7188766565441185)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 45),
   np.float64(6.716579784819295)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 52),
   np.float64(6.7124114684806075)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 58),
   np.float64(6.705922398851899)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 58),
   np.float64(5.273853616304852)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 56),
   np.float64(1.8005894287258521)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 56),
   np.float64(1.321631532961225)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 15, 58, 7),
   np.float64(1.7070317854059738)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 23),
   np.float64(1.7536891271334283)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 15, 59, 55),
   np.float64(1.6088533529090774))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 58),
   np.float64(6.724813554947875)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 20, 0),
   np.float64(6.727345973521839)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 48),
   np.float64(6.726943266979146)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 1, 20, 0),
   np.float64(6.72470102978345)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 20, 0),
   np.float64(6.723841352575142)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 53),
   np.float64(6.724876369112797)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 55),
   np.float64(6.723894355016584)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 54),
   np.float64(6.724448268664892)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 54),
   np.float64(6.723787788694836)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 14),
   np.float64(6.724710324418767)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 54),
   np.float64(6.724587320070454)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 20, 0),
   np.float64(6.724426873869197)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 20, 0, 2),
   np.float64(6.724971496919551)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 43),
   np.float64(6.724125030866415)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 57),
   np.float64(6.725253177069756)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 55),
   np.float64(6.723597041327427)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 1, 20, 0, 1),
   np.float64(6.718847287491486)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 1, 20, 0),
   np.float64(6.716458502649052)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 59),
   np.float64(6.712364718412315)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 57),
   np.float64(6.7057428085341435)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 1, 19, 58, 57),
   np.float64(5.272574483814767)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 37),
   np.float64(1.8005011024324875)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 51),
   np.float64(1.321599717177914)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 1, 20, 0, 2),
   np.float64(1.7069688548895192)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 49),
   np.float64(1.7536509696917375)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 1, 19, 59, 57),
   np.float64(1.6088294259028386))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 57),
   np.float64(6.724875168078867)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 58),
   np.float64(6.7273765860665025)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 38),
   np.float64(6.726959481981123)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(6.724722698252681)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 59),
   np.float64(6.723837611693547)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(6.724898749306502)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 59),
   np.float64(6.723933154089649)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(6.724461676561269)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 59),
   np.float64(6.7237517508097975)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 1),
   np.float64(6.724706455124125)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 2, 0, 0),
   np.float64(6.724577868157417)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 59),
   np.float64(6.724427292502454)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 34),
   np.float64(6.724944020479659)),
  'USEG:UNDS:3450:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 1),
   np.float64(6.724164547794888)),
  'USEG:UNDS:3650:KAct': (datetime.datetime(2026, 6, 1, 23, 58, 2),
   np.float64(6.72525658093155)),
  'USEG:UNDS:3750:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(6.7236029759169105)),
  'USEG:UNDS:3850:KAct': (datetime.datetime(2026, 6, 2, 0, 0),
   np.float64(6.718806284540772)),
  'USEG:UNDS:3950:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(6.716472515652286)),
  'USEG:UNDS:4050:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 52),
   np.float64(6.712351616952581)),
  'USEG:UNDS:4150:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 57),
   np.float64(6.705739734676176)),
  'USEG:UNDS:4250:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(5.272131828196988)),
  'USEG:UNDS:4350:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 55),
   np.float64(1.8004859898985177)),
  'USEG:UNDS:4450:KAct': (datetime.datetime(2026, 6, 1, 23, 59, 48),
   np.float64(1.3215952260419954)),
  'USEG:UNDS:4550:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 1),
   np.float64(1.7069587272578999)),
  'USEG:UNDS:4650:KAct': (datetime.datetime(2026, 6, 1, 23, 56, 32),
   np.float64(1.7536429770897768)),
  'USEG:UNDS:4750:KAct': (datetime.datetime(2026, 6, 2, 0, 0, 2),
   np.float64(1.6088304091308137))},
 {'USEG:UNDS:2150:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 59),
   np.float64(6.724838010008938)),
  'USEG:UNDS:2250:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 56),
   np.float64(6.727354796714386)),
  'USEG:UNDS:2350:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 58),
   np.float64(6.726957666203108)),
  'USEG:UNDS:2450:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 51),
   np.float64(6.7246863981677105)),
  'USEG:UNDS:2550:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 58),
   np.float64(6.72383664879387)),
  'USEG:UNDS:2650:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 52),
   np.float64(6.724882411574107)),
  'USEG:UNDS:2750:KAct': (datetime.datetime(2026, 6, 2, 4, 0, 1),
   np.float64(6.723893218239785)),
  'USEG:UNDS:2850:KAct': (datetime.datetime(2026, 6, 2, 4, 0),
   np.float64(6.724409868722238)),
  'USEG:UNDS:2950:KAct': (datetime.datetime(2026, 6, 2, 4, 0, 2),
   np.float64(6.7238021534118015)),
  'USEG:UNDS:3050:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 7),
   np.float64(6.724702704233038)),
  'USEG:UNDS:3150:KAct': (datetime.datetime(2026, 6, 2, 4, 0, 2),
   np.float64(6.724527836681204)),
  'USEG:UNDS:3250:KAct': (datetime.datetime(2026, 6, 2, 3, 59, 59),
   np.float64(6.724409944067121)),
  'USEG:UNDS:3350:KAct': (datetime.datetime(2026, 6, 2, 4, 0),

## XLEAP detection
We say that XLEAP is happening when:
>There exists a group of at least 4 undulators whose $K$'s are increasing by at least $4\rho$ per undulator ($\rho \sim 0.3$).

To find such a group, we make a boolean array from the K array indicating where $K_{i}\geq K_{i-1}+4\rho$. Then we use "binary erosion" and "binary expansion" to filter for runs of at least $n=4$ consecutive increases of $\Delta K \geq 4\rho$.

In [20]:
# Build a display DataFrame from the K snapshots using nominal request times.
import pandas as pd

und_nums = [re.search(r'USEG:UNDS:(\d+):KAct', pv).group(1) for pv in kact_pvs]
nominal_times = [start + i * coarse_delta for i in range(len(k_snapshots))]

kvals_df = pd.DataFrame(
    data=[
        [snapshot[pv][1] if pv in snapshot else np.nan for pv in kact_pvs]
        for snapshot in k_snapshots
    ],
    index=nominal_times,
    columns=und_nums,
)
kvals_df.index.name = 'NOMINAL time'
kvals_df.columns.name = 'Undulator'
kvals_df

Undulator,2150,2250,2350,2450,2550,2650,2750,2850,2950,3050,...,3850,3950,4050,4150,4250,4350,4450,4550,4650,4750
NOMINAL time,,,,,,,,,,,,,,,,,,,,,
2026-06-01 00:00:00,6.725062,6.726964,6.726537,6.724772,6.724058,6.724961,6.724410,6.724681,6.724374,6.724943,...,6.718377,6.715974,6.711830,6.704956,1.372594,1.800388,1.321534,1.706796,1.753548,1.608738
2026-06-01 04:00:00,6.725048,6.727050,6.726618,6.724772,6.724007,6.725005,6.724353,6.724656,6.724377,6.724938,...,6.718459,6.716062,6.711892,6.705037,1.372595,1.800382,1.321519,1.706790,1.753538,1.608735
2026-06-01 08:00:00,6.725297,6.727509,6.727144,6.725134,6.724268,6.725200,6.724302,6.724814,6.724317,6.725221,...,6.718902,6.716551,6.712324,6.705563,0.000009,1.800506,1.321593,1.707004,1.753619,1.608807
2026-06-01 12:00:00,6.725227,6.727591,6.727217,6.725078,6.724149,6.725135,6.724231,6.724723,6.724106,6.725038,...,6.719045,6.716647,6.712492,6.705936,0.000009,1.800545,1.321635,1.707044,1.753689,1.608852
2026-06-01 16:00:00,6.725010,6.727479,6.727086,6.724912,6.723983,6.725029,6.724034,6.724583,6.723920,6.724834,...,6.718877,6.716580,6.712411,6.705922,5.273854,1.800589,1.321632,1.707032,1.753689,1.608853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-13 00:00:00,4.236782,2.172589,5.302483,2.522315,4.087217,4.087118,4.087115,4.105844,4.124674,4.143247,...,2.798312,2.802503,2.805829,2.809314,2.812814,3.501500,3.505684,1.286586,1.758174,2.227364
2026-06-13 04:00:00,6.150169,6.322660,6.295147,6.318123,6.427117,6.426067,6.425407,6.424751,6.424281,6.423578,...,4.293625,4.126488,4.197627,4.323471,4.292008,5.280837,4.719855,4.718880,5.247307,4.714026
2026-06-13 08:00:00,5.830725,5.829638,5.828500,5.827533,5.826258,5.825119,5.824007,5.822844,5.821774,5.820751,...,5.754611,5.736480,5.715066,5.691484,5.665632,1.226410,1.082804,1.203852,1.196448,1.048642
2026-06-13 12:00:00,5.485421,3.312873,3.237853,3.259351,5.063672,5.063410,5.063389,5.063351,5.123680,5.184031,...,3.728625,3.728976,3.743767,3.758796,3.773693,3.789204,1.082816,1.203886,1.196485,1.048680
2026-06-13 16:00:00,5.501352,3.564280,3.070259,3.153219,5.332227,5.331916,5.332118,5.332092,5.356156,5.380336,...,3.728152,3.728702,3.733371,3.737946,3.742609,4.076136,1.082827,1.203890,1.196498,1.048656

In [21]:
# Binary erosion tests for intuition
from scipy.ndimage import binary_erosion, binary_dilation
def mask_n(arr, n=4):
    structure = [1] * n
    return binary_dilation(
        binary_erosion(arr, structure=structure),
        structure=structure,
    )

mask_n(np.array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])).astype(int)

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [23]:
def dk_to_dgamma(dK, K, gamma):
    return gamma * (np.sqrt(1 + ((K + dK / 2) * dK) / (1 + K**2 / 2)) - 1)

def k_to_dk(kvals_df: pd.DataFrame):
    # Calculate dK by subtracting K from a rolled version of itself (shifted by 1)
    dK_df = kvals_df - kvals_df.shift(1, axis=1)
    return dK_df

def detect_lasing_groups(kvals_df, rho=1e-3, rho_scale=4, n=4):
    '''
    1. Calculate dK by subtracting K from a rolled version of itself (shifted by 1)
    2. Mask dK >= rho * rho_scale
    3. Apply binary erosion and dilation to find contiguous groups of lasing undulators, with a minimum group size of n
    
    '''
    # 1. Calculate dK
    dk = k_to_dk(kvals_df)

    #2. Mask dK >= rho * rho_scale
    at_least_rho = dk >= rho * rho_scale

    # 3. Apply binary erosion and dilation row-by-row along the undulator axis.
    structure = [1] * n
    eroded_and_dilated = at_least_rho.apply(
        lambda row: binary_dilation(
            binary_erosion(row.to_numpy(dtype=bool), structure=structure),
            structure=structure,
        ),
        axis=1,
        result_type='expand',
    )
    eroded_and_dilated.index = kvals_df.index
    eroded_and_dilated.columns = kvals_df.columns
    return eroded_and_dilated

# Lasing group masks are built from dK arrays; add 1 to the left of each group to correct fencepost error when masking K array
dk_lasing_mask = detect_lasing_groups(kvals_df)
dk_group_left_edges = dk_lasing_mask & ~dk_lasing_mask.shift(1, axis=1, fill_value=False)
k_lasing_mask = dk_lasing_mask | dk_group_left_edges.shift(-1, axis=1, fill_value=False)

# Mask K values by lasing groups
lasing_groups = kvals_df[k_lasing_mask]
lasing_groups

Undulator,2150,2250,2350,2450,2550,2650,2750,2850,2950,3050,...,3850,3950,4050,4150,4250,4350,4450,4550,4650,4750
NOMINAL time,,,,,,,,,,,,,,,,,,,,,
2026-06-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-01 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-01 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,4.087115,4.105844,4.124674,4.143247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-13 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-13 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-13 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.063351,5.123680,5.184031,...,NaN,3.728976,3.743767,3.758796,3.773693,3.789204,NaN,NaN,NaN,NaN
2026-06-13 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.332092,5.356156,5.380336,...,NaN,3.728702,3.733371,3.737946,3.742609,4.076136,NaN,NaN,NaN,NaN

After coarse detection of lasing groups, search two hours to either side of each timestamp in which lasing groups appear. Use intervals of `fine_delta` (default: 15 minutes) to fill in the gaps.

In [24]:
fine_delta = globals().get('fine_delta', timedelta(minutes=15))
fine_window = timedelta(hours=2)

coarse_lasing_times = list(lasing_groups.index[lasing_groups.notna().any(axis=1)])

fine_times = set()
for coarse_time in coarse_lasing_times:
    t = coarse_time - fine_window
    while t <= coarse_time + fine_window:
        if start <= t <= end:
            fine_times.add(t)
        t += fine_delta
fine_times = sorted(fine_times)

fine_k_snapshots = [
    _fetch_archiver_snapshot(kact_pvs, from_time=t, to_time=t + snapshot_delta)
    for t in fine_times
]

fine_kvals_df = pd.DataFrame(
    data=[
        [snapshot[pv][1] if pv in snapshot else np.nan for pv in kact_pvs]
        for snapshot in fine_k_snapshots
    ],
    index=fine_times,
    columns=und_nums,
)
fine_kvals_df.index.name = 'NOMINAL time'
fine_kvals_df.columns.name = 'Undulator'

fine_snapshot_times_df = pd.DataFrame(
    data=[
        [snapshot[pv][0] if pv in snapshot else pd.NaT for pv in kact_pvs]
        for snapshot in fine_k_snapshots
    ],
    index=fine_times,
    columns=und_nums,
)
fine_snapshot_times_df.index.name = 'NOMINAL time'
fine_snapshot_times_df.columns.name = 'Undulator'

fine_dk_lasing_mask = detect_lasing_groups(fine_kvals_df)
fine_dk_group_left_edges = fine_dk_lasing_mask & ~fine_dk_lasing_mask.shift(1, axis=1, fill_value=False)
fine_k_lasing_mask = fine_dk_lasing_mask | fine_dk_group_left_edges.shift(-1, axis=1, fill_value=False)
fine_lasing_groups = fine_kvals_df[fine_k_lasing_mask]

fine_k_snapshots_df = pd.concat(
    {'K value': fine_kvals_df, 'Snapshot time': fine_snapshot_times_df},
    axis=1,
)
fine_k_snapshots_df.columns.names = ['Field', 'Undulator']

fine_lasing_groups

Undulator,2150,2250,2350,2450,2550,2650,2750,2850,2950,3050,...,3850,3950,4050,4150,4250,4350,4450,4550,4650,4750
NOMINAL time,,,,,,,,,,,,,,,,,,,,,
2026-06-09 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-09 22:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-09 22:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-09 22:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-06-09 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.316114,4.333758,4.351396,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-13 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.311412,5.335339,5.359246,...,NaN,3.712459,3.716944,3.721566,3.726185,4.061869,NaN,NaN,NaN,NaN
2026-06-13 17:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.231503,5.254424,5.277455,...,NaN,3.649225,3.653480,3.657968,3.662337,4.006416,NaN,NaN,NaN,NaN
2026-06-13 17:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.281128,5.304692,5.328169,...,NaN,3.696383,3.700838,3.705432,3.709979,4.047846,NaN,NaN,NaN,NaN
2026-06-13 17:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.331967,5.356198,5.380325,...,NaN,3.728732,3.733287,3.737965,3.742653,4.076392,NaN,NaN,NaN,NaN
2026-06-13 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.231522,5.254492,5.277445,...,NaN,3.649270,3.653484,3.657972,3.662358,4.006383,NaN,NaN,NaN,NaN

# Taper reporting
We take the median change in K of the first undulator group, convert to $\Delta \gamma$, and divide by one undulator length in units of time:
$$
T_u = \frac{L_u}{c} \approx \frac{3.4\text{ m}}{3\cdot 10^8 \text{ m/s}} \sim 1.13\cdot10^{-8}\text{ s} = 11.3\text{ ns}
$$

In [ ]:
L_u = 3.4 # Undulator length in meters
c = 299792458 # Speed of light in m/s
T_u = L_u / c # Undulator period in seconds

# isolate the first lasing group (= contiguous GROUP of undulators with dK > threshold) for each time
for time, undulator_values in fine_lasing_groups.iterrows():
    lasing_undulators = undulator_values.index[undulator_values.notna()]
    if len(lasing_undulators) == 0:
        continue
    first_group_start = lasing_undulators[0]
    first_group_end = first_group_start
    for und in lasing_undulators[1:]:
        if und == first_group_end + 1:
            first_group_end = und
        else:
            break
    print(f'Time: {time}, First lasing group: Undulators {first_group_start} to {first_group_end}')

AttributeError: 'tuple' object has no attribute 'notna'

# XLEAP Data Server
Using the above, we declare a function that takes in a start and end time and returns a list of data objects every quarter-hour between start and end times, including the precise start and end times. The data object contains:
```
{
    'xleap_on': bool            # False if no lasing undulator groups are detected; true otherwise
    'K_lasing': dict(str,float) # map from lasing und number to K (only lasing unds shown)
    'n_und':    int             # len(K_lasing)
    'taper':    float           # Taper of FIRST lasing group using median $\Delta K$ in MeV/fs
}
```